services:
  api:
    build:
      context: .
      target: dev
    env_file:
      - .env
    ports:
      - "${DEV_PORT}:8000"
    expose:
      - "8000"
    networks:
      - api-network

networks:
  api-network:
    name: gcp-network
