services:
  db:
    image: postgres
    container_name: erp_db_test
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - api-network
    environment:
      - POSTGRES_PASSWORD=password
  api:
    build:
      context: .
      target: dev
    volumes:
      - .:/api
      - /api/node_modules
    env_file:
      - .env
    ports:
      - "${DEV_PORT}:8000"
    expose:
      - "8000"
    networks:
      - api-network

networks:
  api-network:
    name: erp-network
    external: true

volumes:
  pgdata: