# render.yaml
services:
  - type: web
    name: seu-backend-socket
    runtime: node
    repo: https://github.com/seu-usuario/seu-repositorio
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FRONT_HOST
        value: https://seu-frontend.vercel.app
      - key: FRONTEND_URL
        value: https://seu-frontend.vercel.app
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: main